### ISSUE TITLE
gtabview unexpectedly terminates python when there are duplicated column names

### ISSUE THREAD

**Issue by matthewgson** [TabViewer/gtabview#30]
When viewing pandas DataFrame, if there are duplicated column names in DataFrame, gtabview terminates python session. 

Below is code example and result.

>>>data = data[['a','a','b','c']]
>>>view(data)

Traceback (most recent call last):
  File "C:\Python\lib\site-packages\gtabview\viewer.py", line 46, in data
    return self._as_str(self.model.data(index.row(), index.column()))
  File "C:\Python\lib\site-packages\gtabview\models.py", line 230, in data
    return self._data.iat[y, x]
  File "C:\Python\lib\site-packages\pandas\core\indexing.py", line 2270, in __getitem__    return self.obj._get_value(*key, takeable=self._takeable)
  File "C:\Python\lib\site-packages\pandas\core\frame.py", line 2764, in _get_value
    series = self._iget_item_cache(col)
  File "C:\Python\lib\site-packages\pandas\core\generic.py", line 3087, in _iget_item_cache
    lower = self._take(item, axis=self._info_axis_number)
  File "C:\Python\lib\site-packages\pandas\core\generic.py", line 3359, in _take
    verify=True)
  File "C:\Python\lib\site-packages\pandas\core\internals\managers.py", line 1350, in take
    axis=axis, allow_dups=True)
  File "C:\Python\lib\site-packages\pandas\core\internals\managers.py", line 1231, in reindex_indexer
    fill_tuple=(fill_value,))
  File "C:\Python\lib\site-packages\pandas\core\internals\managers.py", line 1256, in _slice_take_blocks_ax0
    slice_or_indexer, self.shape[0], allow_fill=allow_fill)
  File "C:\Python\lib\site-packages\pandas\core\internals\managers.py", line 2026, in _preprocess_slice_or_indexer
    return 'fancy', indexer, len(indexer)
TypeError: len() of unsized object

C:\Users\GS\Desktop\>
After the error message, Python is terminated. 
This is unexpected behavior.

**Comment by wavexx** [comment]
Sadly, this is a bug in pandas.
See my own report from 2015 :/

https://github.com/pandas-dev/pandas/issues/11754

**Comment by axil** [comment]
It looks as if the issue in pandas has been resolved recently. I guess it should be safe to close this issue now.

**Comment by wavexx** [comment]
Verified also on my side. Closing!
